import type { HistoryAskDomain, HistoryAskQuickQuestion, HistoryAskResponse, HistoryOntologyDraft, HistoryOntologyTerm, LlmConfig, LlmConfigDraft } from "../types";
import { request } from "./client";

export async function askHistory(question: string, skillIds: string[] = [], modelName = "", domainCode: "history" | "todos" | "knowledge" | "english_materials" = "history"): Promise<HistoryAskResponse> {
  return request<HistoryAskResponse>("/api/history-ask", { method: "POST", body: JSON.stringify({ question, skill_ids: skillIds, execution_provider: "history_ask_llm", model_name: modelName, domain_code: domainCode }) });
}
export async function fetchHistoryAskLlmConfigs(): Promise<{ items: LlmConfig[] }> { return request<{ items: LlmConfig[] }>("/api/history-ask/llm-configs"); }
export async function createHistoryAskLlmConfig(draft: LlmConfigDraft): Promise<LlmConfig> { return request<LlmConfig>("/api/history-ask/llm-configs", { method: "POST", invalidatePrefixes: ["/api/history-ask/llm-configs"], body: JSON.stringify(draft) }); }
export async function updateHistoryAskLlmConfig(id: number, draft: LlmConfigDraft): Promise<LlmConfig> { return request<LlmConfig>(`/api/history-ask/llm-configs/${id}`, { method: "PUT", invalidatePrefixes: ["/api/history-ask/llm-configs"], body: JSON.stringify(draft) }); }
export async function deleteHistoryAskLlmConfig(id: number): Promise<void> { return request<void>(`/api/history-ask/llm-configs/${id}`, { method: "DELETE", invalidatePrefixes: ["/api/history-ask/llm-configs"] }); }
export async function fetchHistoryAskDomains(): Promise<{ items: HistoryAskDomain[] }> { return request<{ items: HistoryAskDomain[] }>("/api/history-ask/domains"); }
type HistoryAskDomainCode = "history" | "todos" | "knowledge" | "english_materials";
export async function fetchHistoryAskQuickQuestions(domainCode: HistoryAskDomainCode): Promise<{ items: HistoryAskQuickQuestion[] }> { return request<{ items: HistoryAskQuickQuestion[] }>(`/api/history-ask/quick-questions?domain_code=${domainCode}`); }
export async function createHistoryAskQuickQuestion(question: string, domainCode: HistoryAskDomainCode): Promise<HistoryAskQuickQuestion> { return request<HistoryAskQuickQuestion>("/api/history-ask/quick-questions", { method: "POST", invalidatePrefixes: ["/api/history-ask/quick-questions"], body: JSON.stringify({ question, domain_code: domainCode }) }); }
export async function updateHistoryAskQuickQuestion(id: number, question: string): Promise<HistoryAskQuickQuestion> { return request<HistoryAskQuickQuestion>(`/api/history-ask/quick-questions/${id}`, { method: "PUT", invalidatePrefixes: ["/api/history-ask/quick-questions"], body: JSON.stringify({ question }) }); }
export async function deleteHistoryAskQuickQuestion(id: number): Promise<void> { await request<void>(`/api/history-ask/quick-questions/${id}`, { method: "DELETE", invalidatePrefixes: ["/api/history-ask/quick-questions"] }); }
export async function fetchHistoryOntology(domainCode: HistoryAskDomainCode): Promise<{ items: HistoryOntologyTerm[] }> { return request<{ items: HistoryOntologyTerm[] }>(`/api/history-ask/ontology?domain_code=${domainCode}`); }
function ontologyBody(draft: HistoryOntologyDraft) { return { name: draft.name.trim(), domain_code: draft.domain_code, aliases: draft.aliases.split(/[，,\n]/).map((item) => item.trim()).filter(Boolean), description: draft.description.trim(), visibility: draft.visibility, shared_with_usernames: draft.shared_with_usernames.split(/[，,\n]/).map((item) => item.trim()).filter(Boolean) }; }
export async function createHistoryOntology(draft: HistoryOntologyDraft): Promise<HistoryOntologyTerm> { return request<HistoryOntologyTerm>("/api/history-ask/ontology", { method: "POST", invalidatePrefixes: ["/api/history-ask/ontology"], body: JSON.stringify(ontologyBody(draft)) }); }
export async function updateHistoryOntology(id: number, draft: HistoryOntologyDraft): Promise<HistoryOntologyTerm> { return request<HistoryOntologyTerm>(`/api/history-ask/ontology/${id}`, { method: "PUT", invalidatePrefixes: ["/api/history-ask/ontology"], body: JSON.stringify(ontologyBody(draft)) }); }
export async function deleteHistoryOntology(id: number): Promise<void> { await request<void>(`/api/history-ask/ontology/${id}`, { method: "DELETE", invalidatePrefixes: ["/api/history-ask/ontology"] }); }
